import type { Metadata } from 'next'
import { Geist, Geist_Mono, Silkscreen } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

const silkscreen = Silkscreen({
  variable: '--font-silkscreen',
  subsets: ['latin'],
  weight: ['400', '700']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${silkscreen.variable} ${silkscreen.variable} antialiased`}
      >
        {/*
          MESH GRADIENT BACKGROUND - EASY THEME SWITCHING

          Available themes (just change the class name below):
          - mesh-lavender        → Purple/Blue (Original)
          - mesh-emerald         → Green Paradise
          - mesh-ocean           → Deep Blue
          - mesh-grayscale       → Monochrome
          - mesh-rainbow         → Full Spectrum
          - mesh-sunset          → Warm Orange/Pink
          - mesh-forest          → Deep Green/Earth
          - mesh-candy           → Pink/Purple Sweet
          - mesh-cyber           → Neon Tech
          - mesh-peach           → Soft Warm
          - mesh-northern-lights → Aurora Borealis (ANIMATED!)
        */}
        <div className='mesh-gradient-container mesh-northern-lights'>
          <div className='gradient-blob blob-1'></div>
          <div className='gradient-blob blob-2'></div>
          <div className='gradient-blob blob-3'></div>
          <div className='gradient-blob blob-4'></div>
          <div className='gradient-blob blob-5'></div>
          <div className='mesh-overlay'></div>
          <div className='fade-to-white'></div>
        </div>

        {/* Main Content */}
        <div className='relative z-10'>{children}</div>
      </body>
    </html>
  )
}
